In [1]:
import pandas as pd
import numpy as np
import os
from pathlib import Path

# 📁 Định nghĩa đường dẫn gốc
BASE_PATH = r"C:\Users\ThaoMuy\Downloads\Recommend_System"
DATA_USERS = os.path.join(BASE_PATH, "backend", "data", "users")

print(f"📁 BASE_PATH: {BASE_PATH}")
print(f"📂 DATA_USERS: {DATA_USERS}")

📁 BASE_PATH: C:\Users\ThaoMuy\Downloads\Recommend_System
📂 DATA_USERS: C:\Users\ThaoMuy\Downloads\Recommend_System\backend\data\users

In [3]:
# 📂 Đọc file CSV users
csv_path = os.path.join(DATA_USERS, "users.csv")
df = pd.read_csv(csv_path)

print(f"📂 Đã đọc file: {csv_path}")
print(f"📊 Tổng số dòng: {len(df)}")
print(f"📊 Tổng số cột: {len(df.columns)}")
print("\n" + "="*80)

📂 Đã đọc file: C:\Users\ThaoMuy\Downloads\Recommend_System\backend\data\users\users.csv
📊 Tổng số dòng: 271
📊 Tổng số cột: 21

================================================================================

In [4]:
# 📋 Hiển thị tất cả các cột và kiểu dữ liệu
print("📋 DANH SÁCH CÁC CỘT TRONG DATASET:")
print("="*80)
for i, col in enumerate(df.columns, 1):
    dtype = df[col].dtype
    non_null = df[col].notna().sum()
    null_count = df[col].isna().sum()
    print(f"{i:2d}. {col}")
    print(f"    - Kiểu dữ liệu: {dtype}")
    print(f"    - Số giá trị không null: {non_null}/{len(df)} ({non_null/len(df)*100:.1f}%)")
    print(f"    - Số giá trị null: {null_count} ({null_count/len(df)*100:.1f}%)")
    print()

📋 DANH SÁCH CÁC CỘT TRONG DATASET:
================================================================================
 1. Dấu thời gian
    - Kiểu dữ liệu: object
    - Số giá trị không null: 271/271 (100.0%)
    - Số giá trị null: 0 (0.0%)

 2. Giới tính (Gender)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 271/271 (100.0%)
    - Số giá trị null: 0 (0.0%)

 3.   Độ tuổi (Age)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 271/271 (100.0%)
    - Số giá trị null: 0 (0.0%)

 4.   Bạn có hạn chế chế độ ăn nào không? (Do you have any dietary restrictions?)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 271/271 (100.0%)
    - Số giá trị null: 0 (0.0%)

 5.   Bạn có dị ứng với thực phẩm nào không? (Do you have any food allergies?)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 271/271 (100.0%)
    - Số giá trị null: 0 (0.0%)

 6. Bạn thường quan tâm đến loại bữa ăn nào? (Which type of meal do you usually care about?)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 269/271 (99.3%)
    - Số giá trị null: 2 (0.7%)

 7. Mức độ kỹ năng nấu ăn của bạn là gì? (Your cooking skill level)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 271/271 (100.0%)
    - Số giá trị null: 0 (0.0%)

 8. Bạn có bao nhiêu thời gian để nấu ăn trung bình? (How much time do you usually have to cook?)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 271/271 (100.0%)
    - Số giá trị null: 0 (0.0%)

 9.  Bạn yêu thích món ăn của quốc gia nào? (Which country’s cuisine do you like?)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 271/271 (100.0%)
    - Số giá trị null: 0 (0.0%)

10. Bạn thích những món ăn Việt Nam nào sau đây? (Which Vietnamese dishes do you like?)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 259/271 (95.6%)
    - Số giá trị null: 12 (4.4%)

11. Bạn thích những món ăn Thái Lan nào sau đây? (Which Thai dishes do you like?)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 265/271 (97.8%)
    - Số giá trị null: 6 (2.2%)

12. Bạn thích những món ăn Trung Quốc nào sau đây? (Which Chinese dishes do you like?)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 262/271 (96.7%)
    - Số giá trị null: 9 (3.3%)

13. Bạn thích những món ăn Pháp nào sau đây? (Which French dishes do you like?)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 235/271 (86.7%)
    - Số giá trị null: 36 (13.3%)

14. Bạn thích những món ăn Ấn Độ nào sau đây? (Which Indian dishes do you like?)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 269/271 (99.3%)
    - Số giá trị null: 2 (0.7%)

15. Bạn thích những món ăn Ý nào sau đây? (Which Italian dishes do you like?)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 265/271 (97.8%)
    - Số giá trị null: 6 (2.2%)

16. Bạn thích những món ăn Nhật Bản nào sau đây? (Which Japanese dishes do you like?)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 269/271 (99.3%)
    - Số giá trị null: 2 (0.7%)

17. Bạn thích những món ăn Hàn Quốc nào sau đây? (Which Korean dishes do you like?)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 253/271 (93.4%)
    - Số giá trị null: 18 (6.6%)

18. Bạn thích những món ăn Mỹ? (Which American dishes do you like?)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 120/271 (44.3%)
    - Số giá trị null: 151 (55.7%)

19. Có món ăn nào bạn thích mà chưa được đề cập trong danh sách trên không? (nếu có)
Is there any dish you like that was not mentioned in the list above?
    - Kiểu dữ liệu: object
    - Số giá trị không null: 211/271 (77.9%)
    - Số giá trị null: 60 (22.1%)

20. Họ và tên (Full Name)
    - Kiểu dữ liệu: object
    - Số giá trị không null: 211/271 (77.9%)
    - Số giá trị null: 60 (22.1%)

21. Địa chỉ email
    - Kiểu dữ liệu: float64
    - Số giá trị không null: 0/271 (0.0%)
    - Số giá trị null: 271 (100.0%)

In [5]:
# 🔍 Xem thông tin tổng quan về dataset
print("🔍 THÔNG TIN TỔNG QUAN VỀ DATASET:")
print("="*80)
df.info()

🔍 THÔNG TIN TỔNG QUAN VỀ DATASET:
================================================================================
<class 'pandas.core.frame.DataFrame'>
Index: 271 entries, 03/10/2025 21:34:22 to 07/10/2025 20:06:33
Data columns (total 21 columns):
 #   Column                                                                                                                                                  Non-Null Count  Dtype
---  ------                                                                                                                                                  --------------  -----
 0   Dấu thời gian                                                                                                                                           271 non-null    object
 1   Giới tính (Gender)                                                                                                                                      271 non-null    object
 2     Độ tuổi (Age)                                                                                                                                         271 non-null    object
 3     Bạn có hạn chế chế độ ăn nào không? (Do you have any dietary restrictions?)                                                                           271 non-null    object
 4     Bạn có dị ứng với thực phẩm nào không? (Do you have any food allergies?)                                                                              271 non-null    object
 5   Bạn thường quan tâm đến loại bữa ăn nào? (Which type of meal do you usually care about?)                                                                269 non-null    object
 6   Mức độ kỹ năng nấu ăn của bạn là gì? (Your cooking skill level)                                                                                         271 non-null    object
 7   Bạn có bao nhiêu thời gian để nấu ăn trung bình? (How much time do you usually have to cook?)                                                           271 non-null    object
 8    Bạn yêu thích món ăn của quốc gia nào? (Which country’s cuisine do you like?)                                                                          271 non-null    object
 9   Bạn thích những món ăn Việt Nam nào sau đây? (Which Vietnamese dishes do you like?)                                                                     259 non-null    object
 10  Bạn thích những món ăn Thái Lan nào sau đây? (Which Thai dishes do you like?)                                                                           265 non-null    object
 11  Bạn thích những món ăn Trung Quốc nào sau đây? (Which Chinese dishes do you like?)                                                                      262 non-null    object
 12  Bạn thích những món ăn Pháp nào sau đây? (Which French dishes do you like?)                                                                             235 non-null    object
 13  Bạn thích những món ăn Ấn Độ nào sau đây? (Which Indian dishes do you like?)                                                                            269 non-null    object
 14  Bạn thích những món ăn Ý nào sau đây? (Which Italian dishes do you like?)                                                                               265 non-null    object
 15  Bạn thích những món ăn Nhật Bản nào sau đây? (Which Japanese dishes do you like?)                                                                       269 non-null    object
 16  Bạn thích những món ăn Hàn Quốc nào sau đây? (Which Korean dishes do you like?)                                                                         253 non-null    object
 17  Bạn thích những món ăn Mỹ? (Which American dishes do you like?)                                                                                         120 non-null    object
 18  Có món ăn nào bạn thích mà chưa được đề cập trong danh sách trên không? (nếu có)
Is there any dish you like that was not mentioned in the list above?  211 non-null    object
 19  Họ và tên (Full Name)                                                                                                                                   211 non-null    object
 20  Địa chỉ email                                                                                                                                           0 non-null      float64
dtypes: float64(1), object(20)
memory usage: 46.6+ KB

In [6]:
# 👀 Xem 5 dòng đầu tiên
print("👀 5 DÒNG ĐẦU TIÊN:")
print("="*80)
df.head()

👀 5 DÒNG ĐẦU TIÊN:
================================================================================

,Dấu thời gian,Giới tính (Gender),Độ tuổi (Age),Bạn có hạn chế chế độ ăn nào không? (Do you have any dietary restrictions?),Bạn có dị ứng với thực phẩm nào không? (Do you have any food allergies?),Bạn thường quan tâm đến loại bữa ăn nào? (Which type of meal do you usually care about?),Mức độ kỹ năng nấu ăn của bạn là gì? (Your cooking skill level),Bạn có bao nhiêu thời gian để nấu ăn trung bình? (How much time do you usually have to cook?),Bạn yêu thích món ăn của quốc gia nào? (Which country’s cuisine do you like?),Bạn thích những món ăn Việt Nam nào sau đây? (Which Vietnamese dishes do you like?),...,Bạn thích những món ăn Trung Quốc nào sau đây? (Which Chinese dishes do you like?),Bạn thích những món ăn Pháp nào sau đây? (Which French dishes do you like?),Bạn thích những món ăn Ấn Độ nào sau đây? (Which Indian dishes do you like?),Bạn thích những món ăn Ý nào sau đây? (Which Italian dishes do you like?),Bạn thích những món ăn Nhật Bản nào sau đây? (Which Japanese dishes do you like?),Bạn thích những món ăn Hàn Quốc nào sau đây? (Which Korean dishes do you like?),Bạn thích những món ăn Mỹ? (Which American dishes do you like?),Có món ăn nào bạn thích mà chưa được đề cập trong danh sách trên không? (nếu có)\r\nIs there any dish you like that was not mentioned in the list above?,Họ và tên (Full Name),Địa chỉ email
03/10/2025 21:34:22,Nam (Male),18 – 24 tuổi (18 – 24),Dị ứng (Allergies ),Hải sản (Seafood),"Bữa sáng (Breakfast), Bữa trưa (Lunch), Bữa tố...",Người mới bắt đầu (Beginner),< 15 phút (< 15 minutes),"Việt Nam (Vietnamese), Trung Quốc (Chinese), Ý...","Phở (Pho), Bánh mì (Banh Mi), Bún chả (Grilled...",NaN,...,"Croissant (Croissant), Bánh mì Baguette (Bague...","Cơm Biryani (Biryani), Gà bơ (Butter Chicken),...","Pizza (Pizza), Mì Ý Spaghetti Carbonara (Spagh...","Sushi (Sushi), Ramen (Ramen), Tempura (Tempura...","Kimchi (Kimchi), Cơm trộn Bibimbap (Bibimbap),...",NaN,NaN,NaN,NaN,NaN
03/10/2025 23:30:38,Nam (Male),25 – 34 tuổi (25 – 34),Ít đường (Low sugar),Không dị ứng (No allergies),"Bữa sáng (Breakfast), Bữa trưa (Lunch), Bữa tố...",Người mới bắt đầu (Beginner),30 – 60 phút (30 – 60 minutes),"Việt Nam (Vietnamese), Nhật Bản (Japanese), Hà...","Phở (Pho), Bánh mì (Banh Mi), Bún chả (Grilled...","Pad Thái (Pad Thai), Canh Tom Yum (Tom Yum Sou...",...,Croissant (Croissant),Cà ri Tikka Masala (Chicken Tikka Masala),"Pizza (Pizza), Mì Ý Spaghetti Carbonara (Spagh...","Sushi (Sushi), Ramen (Ramen), Udon (Udon noodles)","Kimchi (Kimchi), Cơm trộn Bibimbap (Bibimbap),...",NaN,NaN,NaN,NaN,NaN
04/10/2025 0:00:53,Nữ (Female),18 – 30 tuổi (18 – 30),Không có hạn chế (No restrictions),Không dị ứng (No allergies),"Bữa trưa (Lunch), Bữa tối (Dinner)",Trung bình (Intermediate),30 – 60 phút (30 – 60 minutes),Việt Nam (Vietnamese),Phở (Pho),Pad Thái (Pad Thai),...,Bánh mì Baguette (Baguette),Samosa (Samosa),Mì Ý Spaghetti Carbonara (Spaghetti Carbonara),Sushi (Sushi),Kimchi (Kimchi),NaN,NaN,NaN,NaN,NaN
04/10/2025 0:05:58,Nam (Male),30 – 34 tuổi (30 – 34),Không có hạn chế (No restrictions),Không dị ứng (No allergies),Tráng miệng (Dessert),Trung bình (Intermediate),< 15 phút (< 15 minutes),Việt Nam (Vietnamese),Bún chả (Grilled Pork with Vermicelli),Gỏi đu đủ Som Tum (Papaya Salad),...,Croissant (Croissant),Gà bơ (Butter Chicken),Pizza (Pizza),Okonomiyaki (Japanese Pancake),Gà rán Hàn Quốc (Korean Fried Chicken),NaN,NaN,NaN,NaN,NaN
04/10/2025 0:05:59,Nữ (Female),18 – 30 tuổi (18 – 30),Dị ứng (Allergies ),Không dị ứng (No allergies),Tráng miệng (Dessert),Người mới bắt đầu (Beginner),60 phút (> 60 minutes),Ấn Độ (Indian),Bánh mì (Banh Mi),Xôi xoài (Mango Sticky Rice),...,Crème Brûlée (Crème Brûlée),Cơm Biryani (Biryani),Mì Ý Spaghetti Carbonara (Spaghetti Carbonara),Ramen (Ramen),Cơm trộn Bibimbap (Bibimbap),NaN,NaN,NaN,NaN,NaN

In [7]:
# 📊 Phân tích từng cột quan trọng

print("📊 PHÂN TÍCH CHI TIẾT CÁC CỘT:")
print("="*80)

# 1. Dấu thời gian (Timestamp)
if 'Dấu thời gian' in df.columns:
    print("\n1️⃣ DẤU THỜI GIAN (Timestamp):")
    print(f"   - Số lượng: {df['Dấu thời gian'].notna().sum()}")
    print(f"   - Dòng đầu tiên: {df['Dấu thời gian'].iloc[0] if df['Dấu thời gian'].notna().any() else 'N/A'}")
    print(f"   - Dòng cuối cùng: {df['Dấu thời gian'].iloc[-1] if df['Dấu thời gian'].notna().any() else 'N/A'}")

# 2. Giới tính
if 'Giới tính (Gender) ' in df.columns:
    print("\n2️⃣ GIỚI TÍNH (Gender):")
    gender_counts = df['Giới tính (Gender) '].value_counts()
    print(gender_counts)
    print(f"   - Tổng số: {gender_counts.sum()}")

# 3. Độ tuổi
if '  Độ tuổi (Age)  ' in df.columns:
    print("\n3️⃣ ĐỘ TUỔI (Age):")
    age_counts = df['  Độ tuổi (Age)  '].value_counts()
    print(age_counts)
    print(f"   - Tổng số: {age_counts.sum()}")

# 4. Hạn chế chế độ ăn
if '  Bạn có hạn chế chế độ ăn nào không? (Do you have any dietary restrictions?)  ' in df.columns:
    print("\n4️⃣ HẠN CHẾ CHẾ ĐỘ ĂN (Dietary Restrictions):")
    diet_col = '  Bạn có hạn chế chế độ ăn nào không? (Do you have any dietary restrictions?)  '
    diet_counts = df[diet_col].value_counts()
    print(diet_counts)
    print(f"   - Tổng số: {diet_counts.sum()}")

# 5. Dị ứng thực phẩm
if '  Bạn có dị ứng với thực phẩm nào không? (Do you have any food allergies?)  ' in df.columns:
    print("\n5️⃣ DỊ ỨNG THỰC PHẨM (Food Allergies):")
    allergy_col = '  Bạn có dị ứng với thực phẩm nào không? (Do you have any food allergies?)  '
    allergy_counts = df[allergy_col].value_counts()
    print(allergy_counts)
    print(f"   - Tổng số: {allergy_counts.sum()}")

# 6. Loại bữa ăn quan tâm
if 'Bạn thường quan tâm đến loại bữa ăn nào? (Which type of meal do you usually care about?)' in df.columns:
    print("\n6️⃣ LOẠI BỮA ĂN QUAN TÂM (Meal Types):")
    meal_col = 'Bạn thường quan tâm đến loại bữa ăn nào? (Which type of meal do you usually care about?)'
    meal_counts = df[meal_col].value_counts()
    print(meal_counts.head(10))
    print(f"   - Tổng số: {meal_counts.sum()}")

# 7. Mức độ kỹ năng nấu ăn
if 'Mức độ kỹ năng nấu ăn của bạn là gì? (Your cooking skill level)' in df.columns:
    print("\n7️⃣ MỨC ĐỘ KỸ NĂNG NẤU ĂN (Cooking Skill Level):")
    skill_col = 'Mức độ kỹ năng nấu ăn của bạn là gì? (Your cooking skill level)'
    skill_counts = df[skill_col].value_counts()
    print(skill_counts)
    print(f"   - Tổng số: {skill_counts.sum()}")

# 8. Thời gian nấu ăn
if 'Bạn có bao nhiêu thời gian để nấu ăn trung bình? (How much time do you usually have to cook?)' in df.columns:
    print("\n8️⃣ THỜI GIAN NẤU ĂN (Cooking Time):")
    time_col = 'Bạn có bao nhiêu thời gian để nấu ăn trung bình? (How much time do you usually have to cook?)'
    time_counts = df[time_col].value_counts()
    print(time_counts)
    print(f"   - Tổng số: {time_counts.sum()}")

📊 PHÂN TÍCH CHI TIẾT CÁC CỘT:
================================================================================

1️⃣ DẤU THỜI GIAN (Timestamp):
   - Số lượng: 271
   - Dòng đầu tiên: Nam (Male)
   - Dòng cuối cùng: Nữ (Female)

2️⃣ GIỚI TÍNH (Gender):
Giới tính (Gender)
< 18 tuổi (Under 18)      207
18 – 30 tuổi (18 – 30)     58
30 – 34 tuổi (30 – 34)      3
18 – 24 tuổi (18 – 24)      1
25 – 34 tuổi (25 – 34)      1
45 – 54 tuổi (45 – 54)      1
Name: count, dtype: int64
   - Tổng số: 271

3️⃣ ĐỘ TUỔI (Age):
  Độ tuổi (Age)
Không có hạn chế (No restrictions)                                                                                                                      185
Ít đường (Low sugar)                                                                                                                                     23
Dị ứng (Allergies )                                                                                                                                      13
Ít đường (Low sugar), Ít muối (Low salt)                                                                                                                  6
Không có hạn chế (No restrictions), Ít đường (Low sugar)                                                                                                  6
Không gluten (Gluten-free)                                                                                                                                5
Ăn chay / Thuần chay (Vegetarian / Vegan)                                                                                                                 5
Ít muối (Low salt)                                                                                                                                        4
Không gluten (Gluten-free), Ít đường (Low sugar), Ít muối (Low salt), Dị ứng (Allergies )                                                                 3
Không có hạn chế (No restrictions), Ít muối (Low salt)                                                                                                    2
Không có hạn chế (No restrictions), Ít đường (Low sugar), Ít muối (Low salt)                                                                              2
Không có hạn chế (No restrictions), Dị ứng (Allergies )                                                                                                   2
Không có hạn chế (No restrictions), Không gluten (Gluten-free)                                                                                            2
Ăn chay / Thuần chay (Vegetarian / Vegan), Dị ứng (Allergies )                                                                                            2
Không có hạn chế (No restrictions), Ăn chay / Thuần chay (Vegetarian / Vegan), Không gluten (Gluten-free), Ít đường (Low sugar), Dị ứng (Allergies )      1
Ăn chay / Thuần chay (Vegetarian / Vegan), Ít đường (Low sugar), Ít muối (Low salt)                                                                       1
Không có hạn chế (No restrictions), Ăn chay / Thuần chay (Vegetarian / Vegan), Không gluten (Gluten-free)                                                 1
Không có hạn chế (No restrictions), Ăn chay / Thuần chay (Vegetarian / Vegan)                                                                             1
Không gluten (Gluten-free), Dị ứng (Allergies )                                                                                                           1
Ăn chay / Thuần chay (Vegetarian / Vegan), Ít muối (Low salt)                                                                                             1
Không gluten (Gluten-free), Ít đường (Low sugar), Ít muối (Low salt)                                                                                      1
Ít đường (Low sugar), Ít muối (Low salt), Dị ứng (Allergies )                                                                                             1
Ăn chay / Thuần chay (Vegetarian / Vegan), Không gluten (Gluten-free)                                                                                     1
Không có hạn chế (No restrictions), Không gluten (Gluten-free), Ít đường (Low sugar)                                                                      1
Không có hạn chế (No restrictions), Không gluten (Gluten-free), Ít đường (Low sugar), Ít muối (Low salt)                                                  1
Name: count, dtype: int64
   - Tổng số: 271

4️⃣ HẠN CHẾ CHẾ ĐỘ ĂN (Dietary Restrictions):
  Bạn có hạn chế chế độ ăn nào không? (Do you have any dietary restrictions?)
Không dị ứng (No allergies)                                                                                                                                                                          227
Hải sản (Seafood)                                                                                                                                                                                     25
Đậu phộng (Peanuts)                                                                                                                                                                                    4
Các loại hạt khác (Other nuts)                                                                                                                                                                         3
Sữa / Lactose (Milk / Dairy)                                                                                                                                                                           2
Trứng (Eggs)                                                                                                                                                                                           1
Đậu phộng (Peanuts), Các loại hạt khác (Other nuts)                                                                                                                                                    1
Hải sản (Seafood), Sữa / Lactose (Milk / Dairy), Trứng (Eggs)                                                                                                                                          1
Hải sản (Seafood), Đậu phộng (Peanuts)                                                                                                                                                                 1
Hải sản (Seafood), Đậu phộng (Peanuts), Các loại hạt khác (Other nuts), Sữa / Lactose (Milk / Dairy), Trứng (Eggs), Lúa mì / Gluten (Wheat / Gluten), Đậu nành (Soy), Không dị ứng (No allergies)      1
Đậu phộng (Peanuts), Không dị ứng (No allergies)                                                                                                                                                       1
Đậu nành (Soy)                                                                                                                                                                                         1
Hải sản (Seafood), Đậu phộng (Peanuts), Các loại hạt khác (Other nuts), Sữa / Lactose (Milk / Dairy), Trứng (Eggs), Lúa mì / Gluten (Wheat / Gluten), Đậu nành (Soy)                                   1
Lúa mì / Gluten (Wheat / Gluten)                                                                                                                                                                       1
Hải sản (Seafood), Đậu nành (Soy)                                                                                                                                                                      1
Name: count, dtype: int64
   - Tổng số: 271

5️⃣ DỊ ỨNG THỰC PHẨM (Food Allergies):
  Bạn có dị ứng với thực phẩm nào không? (Do you have any food allergies?)
Bữa sáng (Breakfast)                                                                                                                                                30
Bữa tối (Dinner)                                                                                                                                                    29
Bữa sáng (Breakfast), Bữa trưa (Lunch), Bữa tối (Dinner)                                                                                                            28
Bữa sáng (Breakfast), Bữa trưa (Lunch), Bữa tối (Dinner), Khai vị (Appetizer), Tráng miệng (Dessert), Ăn vặt (Snack)                                                28
Bữa trưa (Lunch)                                                                                                                                                    20
Bữa sáng (Breakfast), Bữa trưa (Lunch), Bữa tối (Dinner), Ăn vặt (Snack)                                                                                            13
Ăn vặt (Snack)                                                                                                                                                      13
Bữa trưa (Lunch), Bữa tối (Dinner)                                                                                                                                  11
Bữa tối (Dinner), Ăn vặt (Snack)                                                                                                                                     9
Bữa trưa (Lunch), Bữa tối (Dinner), Ăn vặt (Snack)                                                                                                                   7
Bữa sáng (Breakfast), Bữa trưa (Lunch), Bữa tối (Dinner), Tráng miệng (Dessert), Ăn vặt (Snack)                                                                      7
Bữa sáng (Breakfast), Bữa tối (Dinner)                                                                                                                               5
Bữa sáng (Breakfast), Ăn vặt (Snack)                                                                                                                                 5
Tráng miệng (Dessert)                                                                                                                                                5
Tráng miệng (Dessert), Ăn vặt (Snack)                                                                                                                                4
Bữa sáng (Breakfast), Tráng miệng (Dessert), Ăn vặt (Snack)                                                                                                          4
Bữa tối (Dinner), Tráng miệng (Dessert), Ăn vặt (Snack)                                                                                                              3
Bữa tối (Dinner), Khai vị (Appetizer), Tráng miệng (Dessert), Ăn vặt (Snack)                                                                                         3
Bữa sáng (Breakfast), Bữa trưa (Lunch), Bữa tối (Dinner), Tráng miệng (Dessert)                                                                                      3
Bữa tối (Dinner), Tráng miệng (Dessert)                                                                                                                              3
Bữa sáng (Breakfast), Bữa trưa (Lunch)                                                                                                                               3
Bữa sáng (Breakfast), Tráng miệng (Dessert)                                                                                                                          2
Bữa sáng (Breakfast), Bữa tối (Dinner), Tráng miệng (Dessert)                                                                                                        2
Bữa trưa (Lunch), Tráng miệng (Dessert), Ăn vặt (Snack)                                                                                                              2
Bữa sáng (Breakfast), Bữa trưa (Lunch), Bữa tối (Dinner), Khai vị (Appetizer), Tráng miệng (Dessert)                                                                 2
Bữa trưa (Lunch), Bữa tối (Dinner), Tráng miệng (Dessert)                                                                                                            2
Bữa trưa (Lunch), Bữa tối (Dinner), Khai vị (Appetizer), Tráng miệng (Dessert), Ăn vặt (Snack)                                                                       2
Bữa sáng (Breakfast), Bữa trưa (Lunch), Tráng miệng (Dessert)                                                                                                        2
Bữa sáng (Breakfast), Bữa tối (Dinner), Khai vị (Appetizer)                                                                                                          2
Bữa sáng (Breakfast), Bữa tối (Dinner), Ăn vặt (Snack)                                                                                                               2
Bữa sáng (Breakfast), Bữa trưa (Lunch), Khai vị (Appetizer)                                                                                                          1
Bữa trưa (Lunch), Khai vị (Appetizer), Tráng miệng (Dessert), Ăn vặt (Snack)                                                                                         1
Khai vị (Appetizer), Tráng miệng (Dessert)                                                                                                                           1
Bữa nào cx quan trọng đủ chất là đc                                                                                                                                  1
Bữa trưa (Lunch), Ăn vặt (Snack)                                                                                                                                     1
bữa nào tôi cũng quan tâm                                                                                                                                            1
Hằng ngày                                                                                                                                                            1
Khai vị (Appetizer), Ăn vặt (Snack)                                                                                                                                  1
Bữa sáng (Breakfast), Bữa trưa (Lunch), Bữa tối (Dinner), Khai vị (Appetizer), Tráng miệng (Dessert), Ăn vặt (Snack), Kemmmmm                                        1
Khai vị (Appetizer), Tráng miệng (Dessert), Ăn vặt (Snack)                                                                                                           1
Bữa sáng (Breakfast), Bữa trưa (Lunch), Khai vị (Appetizer), Ăn vặt (Snack)                                                                                          1
tất cả                                                                                                                                                               1
Khai vị (Appetizer)                                                                                                                                                  1
Bữa sáng (Breakfast), Khai vị (Appetizer), Tráng miệng (Dessert), Ăn vặt (Snack)                                                                                     1
Bữa trưa (Lunch), Tráng miệng (Dessert)                                                                                                                              1
Bữa trưa (Lunch), Bữa tối (Dinner), Tráng miệng (Dessert), Ăn vặt (Snack)                                                                                            1
Bữa trưa (Lunch), Khai vị (Appetizer), Ăn vặt (Snack)                                                                                                                1
Bữa sáng (Breakfast), Bữa tối (Dinner), Khai vị (Appetizer), Tráng miệng (Dessert), Ăn vặt (Snack)                                                                   1
Bữa sáng (Breakfast), Bữa trưa (Lunch), Bữa tối (Dinner), Khai vị (Appetizer), Tráng miệng (Dessert), Ăn vặt (Snack), một buổi an thật sang trọng quý phái slay      1
Bữa nào cũng quan trọng                                                                                                                                              1
Name: count, dtype: int64
   - Tổng số: 271

6️⃣ LOẠI BỮA ĂN QUAN TÂM (Meal Types):
Bạn thường quan tâm đến loại bữa ăn nào? (Which type of meal do you usually care about?)
Trung bình (Intermediate)       145
Người mới bắt đầu (Beginner)     94
Thành thạo (Advanced)            30
Name: count, dtype: int64
   - Tổng số: 269

7️⃣ MỨC ĐỘ KỸ NĂNG NẤU ĂN (Cooking Skill Level):
Mức độ kỹ năng nấu ăn của bạn là gì? (Your cooking skill level)
15 – 30 phút (15 – 30 minutes)                                                                                      112
30 – 60 phút (30 – 60 minutes)                                                                                       48
< 15 phút (< 15 minutes)                                                                                             47
60 phút (> 60 minutes)                                                                                               21
15 – 30 phút (15 – 30 minutes), 30 – 60 phút (30 – 60 minutes)                                                       16
< 15 phút (< 15 minutes), 15 – 30 phút (15 – 30 minutes)                                                             12
30 – 60 phút (30 – 60 minutes), 60 phút (> 60 minutes)                                                                6
< 15 phút (< 15 minutes), 15 – 30 phút (15 – 30 minutes), 30 – 60 phút (30 – 60 minutes)                              5
< 15 phút (< 15 minutes), 30 – 60 phút (30 – 60 minutes)                                                              3
< 15 phút (< 15 minutes), 15 – 30 phút (15 – 30 minutes), 30 – 60 phút (30 – 60 minutes), 60 phút (> 60 minutes)      1
Name: count, dtype: int64
   - Tổng số: 271

8️⃣ THỜI GIAN NẤU ĂN (Cooking Time):
Bạn có bao nhiêu thời gian để nấu ăn trung bình? (How much time do you usually have to cook?)
Việt Nam (Vietnamese)                                                                                                                                                                             77
Việt Nam (Vietnamese), Hàn Quốc (Korean)                                                                                                                                                          27
Việt Nam (Vietnamese), Nhật Bản (Japanese), Hàn Quốc (Korean)                                                                                                                                     25
Việt Nam (Vietnamese), Trung Quốc (Chinese), Thái Lan (Thai), Ý (Italian), Nhật Bản (Japanese), Hàn Quốc (Korean), Pháp (French)                                                                  14
Việt Nam (Vietnamese), Trung Quốc (Chinese), Nhật Bản (Japanese), Hàn Quốc (Korean)                                                                                                               10
Việt Nam (Vietnamese), Nhật Bản (Japanese)                                                                                                                                                        10
Hàn Quốc (Korean)                                                                                                                                                                                  9
Việt Nam (Vietnamese), Thái Lan (Thai), Hàn Quốc (Korean)                                                                                                                                          7
Việt Nam (Vietnamese), Trung Quốc (Chinese), Thái Lan (Thai), Nhật Bản (Japanese), Hàn Quốc (Korean)                                                                                               7
Việt Nam (Vietnamese), Trung Quốc (Chinese), Hàn Quốc (Korean)                                                                                                                                     6

📊 ĐÁNH GIÁ CHI TIẾT TỪNG CỘT MÓN ĂN
================================================================================

================================================================================
🍽️ VIỆT NAM
================================================================================
Cột: Bạn thích những món ăn Việt Nam nào sau đây? (Which Vietnamese dishes do you like?)

📈 Thống kê:
   - Số giá trị không null: 259/271 (95.6%)
   - Số giá trị null: 12/271 (4.4%)

📋 Phân tích giá trị:
   - Số bản ghi có dữ liệu: 259
   - Số tổ hợp giá trị duy nhất: 41
   - Tổng số món ăn (sau khi tách): 549
   - Số món ăn duy nhất: 17

🏆 TOP 10 MÓN ĂN PHỔ BIẾN NHẤT:
   ----------------------------------------------------------------------
    1. Canh Tom Yum (Tom Yum Soup)                        | 134/259 |  51.74%
    2. Xôi xoài (Mango Sticky Rice)                       | 125/259 |  48.26%
    3. Pad Thái (Pad Thai)                                | 112/259 |  43.24%
    4. Gỏi đu đủ Som Tum (Papaya Salad)                   | 109/259 |  42.08%
    5. Cà ri xanh (Green Curry)                           |  57/259 |  22.01%
    6. lẩu thái                                           |   1/259 |   0.39%
    7. Cơm rang dứa                                       |   1/259 |   0.39%
    8. k thích món nào ạ                                  |   1/259 |   0.39%
    9. Chưa ăn món thái nào                               |   1/259 |   0.39%
   10. Không biết                                         |   1/259 |   0.39%

📝 MẪU GIÁ TRỊ (5 giá trị đầu tiên):
   1. Pad Thái (Pad Thai), Canh Tom Yum (Tom Yum Soup), Cà ri xanh (Green Curry), Gỏi đu đủ Som Tum (Papay...
   2. Pad Thái (Pad Thai)...
   3. Gỏi đu đủ Som Tum (Papaya Salad)...
   4. Xôi xoài (Mango Sticky Rice)...
   5. Canh Tom Yum (Tom Yum Soup)...

📏 Thống kê độ dài giá trị:
   - Độ dài trung bình: 57.4 ký tự
   - Độ dài ngắn nhất: 7 ký tự
   - Độ dài dài nhất: 155 ký tự

================================================================================
🍽️ THÁI LAN
================================================================================
Cột: Bạn thích những món ăn Thái Lan nào sau đây? (Which Thai dishes do you like?)

📈 Thống kê:
   - Số giá trị không null: 265/271 (97.8%)
   - Số giá trị null: 6/271 (2.2%)

📋 Phân tích giá trị:
   - Số bản ghi có dữ liệu: 265
   - Số tổ hợp giá trị duy nhất: 38
   - Tổng số món ăn (sau khi tách): 586
   - Số món ăn duy nhất: 16

🏆 TOP 10 MÓN ĂN PHỔ BIẾN NHẤT:
   ----------------------------------------------------------------------
    1. Vịt quay Bắc Kinh (Peking Duck)                    | 170/265 |  64.15%
    2. Dim Sum (Dim Sum)                                  | 134/265 |  50.57%
    3. Mì xào Chow Mein (Chow Mein)                       | 110/265 |  41.51%
    4. Đậu hũ Tứ Xuyên (Mapo Tofu)                        |  88/265 |  33.21%
    5. Gà Cung Bảo (Kung Pao Chicken)                     |  73/265 |  27.55%
    6. không thích                                        |   1/265 |   0.38%
    7. Thịt kho đông pha                                  |   1/265 |   0.38%
    8. Không                                              |   1/265 |   0.38%
    9. Không biết                                         |   1/265 |   0.38%
   10. Tâm cay                                            |   1/265 |   0.38%

📝 MẪU GIÁ TRỊ (5 giá trị đầu tiên):
   1. Dim Sum (Dim Sum), Vịt quay Bắc Kinh (Peking Duck), Đậu hũ Tứ Xuyên (Mapo Tofu), Gà Cung Bảo (Kung P...
   2. Vịt quay Bắc Kinh (Peking Duck)...
   3. Dim Sum (Dim Sum), Đậu hũ Tứ Xuyên (Mapo Tofu)...
   4. Dim Sum (Dim Sum)...
   5. Đậu hũ Tứ Xuyên (Mapo Tofu)...

📏 Thống kê độ dài giá trị:
   - Độ dài trung bình: 60.3 ký tự
   - Độ dài ngắn nhất: 5 ký tự
   - Độ dài dài nhất: 160 ký tự

================================================================================
🍽️ TRUNG QUỐC
================================================================================
Cột: Bạn thích những món ăn Trung Quốc nào sau đây? (Which Chinese dishes do you like?)

📈 Thống kê:
   - Số giá trị không null: 262/271 (96.7%)
   - Số giá trị null: 9/271 (3.3%)

📋 Phân tích giá trị:
   - Số bản ghi có dữ liệu: 262
   - Số tổ hợp giá trị duy nhất: 26
   - Tổng số món ăn (sau khi tách): 464
   - Số món ăn duy nhất: 14

🏆 TOP 10 MÓN ĂN PHỔ BIẾN NHẤT:
   ----------------------------------------------------------------------
    1. Bánh mì Baguette (Baguette)                        | 166/262 |  63.36%
    2. Croissant (Croissant)                              | 136/262 |  51.91%
    3. Crème Brûlée (Crème Brûlée)                        |  77/262 |  29.39%
    4. Ratatouille (Ratatouille)                          |  74/262 |  28.24%
    5. Không thích                                        |   2/262 |   0.76%
    6. không thích                                        |   1/262 |   0.38%
    7. Coq au vin với bouillabaisse đỉnh cực              |   1/262 |   0.38%
    8. Ko                                                 |   1/262 |   0.38%
    9. không biết                                         |   1/262 |   0.38%
   10. không thích món nào                                |   1/262 |   0.38%

📝 MẪU GIÁ TRỊ (5 giá trị đầu tiên):
   1. Croissant (Croissant), Bánh mì Baguette (Baguette), Crème Brûlée (Crème Brûlée), Ratatouille (Ratato...
   2. Croissant (Croissant)...
   3. Bánh mì Baguette (Baguette)...
   4. Croissant (Croissant)...
   5. Crème Brûlée (Crème Brûlée)...

📏 Thống kê độ dài giá trị:
   - Độ dài trung bình: 45.2 ký tự
   - Độ dài ngắn nhất: 2 ký tự
   - Độ dài dài nhất: 127 ký tự

================================================================================
🍽️ PHÁP
================================================================================
Cột: Bạn thích những món ăn Pháp nào sau đây? (Which French dishes do you like?)

📈 Thống kê:
   - Số giá trị không null: 235/271 (86.7%)
   - Số giá trị null: 36/271 (13.3%)

📋 Phân tích giá trị:
   - Số bản ghi có dữ liệu: 235
   - Số tổ hợp giá trị duy nhất: 41
   - Tổng số món ăn (sau khi tách): 366
   - Số món ăn duy nhất: 31

🏆 TOP 10 MÓN ĂN PHỔ BIẾN NHẤT:
   ----------------------------------------------------------------------
    1. Cà ri Tikka Masala (Chicken Tikka Masala)          | 120/235 |  51.06%
    2. Gà bơ (Butter Chicken)                             | 100/235 |  42.55%
    3. Cơm Biryani (Biryani)                              |  72/235 |  30.64%
    4. Samosa (Samosa)                                    |  39/235 |  16.60%
    5. không thích                                        |   4/235 |   1.70%
    6. Không thích                                        |   4/235 |   1.70%
    7. Ko                                                 |   2/235 |   0.85%
    8. Không có                                           |   2/235 |   0.85%
    9. Khác                                               |   1/235 |   0.43%
   10. Ko thích                                           |   1/235 |   0.43%

📝 MẪU GIÁ TRỊ (5 giá trị đầu tiên):
   1. Cơm Biryani (Biryani), Gà bơ (Butter Chicken), Cà ri Tikka Masala (Chicken Tikka Masala), Samosa (Sa...
   2. Cà ri Tikka Masala (Chicken Tikka Masala)...
   3. Samosa (Samosa)...
   4. Gà bơ (Butter Chicken)...
   5. Cơm Biryani (Biryani)...

📏 Thống kê độ dài giá trị:
   - Độ dài trung bình: 42.2 ký tự
   - Độ dài ngắn nhất: 2 ký tự
   - Độ dài dài nhất: 134 ký tự

================================================================================
🍽️ ẤN ĐỘ
================================================================================
Cột: Bạn thích những món ăn Ấn Độ nào sau đây? (Which Indian dishes do you like?)

📈 Thống kê:
   - Số giá trị không null: 269/271 (99.3%)
   - Số giá trị null: 2/271 (0.7%)

📋 Phân tích giá trị:
   - Số bản ghi có dữ liệu: 269
   - Số tổ hợp giá trị duy nhất: 19
   - Tổng số món ăn (sau khi tách): 671
   - Số món ăn duy nhất: 10

🏆 TOP 10 MÓN ĂN PHỔ BIẾN NHẤT:
   ----------------------------------------------------------------------
    1. Pizza (Pizza)                                      | 217/269 |  80.67%
    2. Mì Ý Spaghetti Carbonara (Spaghetti Carbonara)     | 215/269 |  79.93%
    3. Tiramisu (Tiramisu)                                | 166/269 |  61.71%
    4. Lasagna (Lasagna)                                  |  67/269 |  24.91%
    5. Khác                                               |   1/269 |   0.37%
    6. Cơm risotto và kem gelato. Lưu ý nhỏ spaghetti là 1 loại sợi mì ạ |   1/269 |   0.37%
    7. còn mì ý nói chung là pasta do mình thấy carbonara ăn được với nhiều loại pasta khác nữa chứ không chỉ spaghetti |   1/269 |   0.37%
    8. và các loại pasta khác ngon hơn nhìu               |   1/269 |   0.37%
    9. Ko                                                 |   1/269 |   0.37%
   10. Ngon là oke                                        |   1/269 |   0.37%

📝 MẪU GIÁ TRỊ (5 giá trị đầu tiên):
   1. Pizza (Pizza), Mì Ý Spaghetti Carbonara (Spaghetti Carbonara), Lasagna (Lasagna), Tiramisu (Tiramisu...
   2. Pizza (Pizza), Mì Ý Spaghetti Carbonara (Spaghetti Carbonara), Tiramisu (Tiramisu)...
   3. Mì Ý Spaghetti Carbonara (Spaghetti Carbonara)...
   4. Pizza (Pizza)...
   5. Mì Ý Spaghetti Carbonara (Spaghetti Carbonara)...

📏 Thống kê độ dài giá trị:
   - Độ dài trung bình: 67.1 ký tự
   - Độ dài ngắn nhất: 2 ký tự
   - Độ dài dài nhất: 286 ký tự

================================================================================
🍽️ Ý
================================================================================
Cột: Bạn thích những món ăn Ý nào sau đây? (Which Italian dishes do you like?)

📈 Thống kê:
   - Số giá trị không null: 265/271 (97.8%)
   - Số giá trị null: 6/271 (2.2%)

📋 Phân tích giá trị:
   - Số bản ghi có dữ liệu: 265
   - Số tổ hợp giá trị duy nhất: 39
   - Tổng số món ăn (sau khi tách): 806
   - Số món ăn duy nhất: 13

🏆 TOP 10 MÓN ĂN PHỔ BIẾN NHẤT:
   ----------------------------------------------------------------------
    1. Sushi (Sushi)                                      | 203/265 |  76.60%
    2. Ramen (Ramen)                                      | 196/265 |  73.96%
    3. Udon (Udon noodles)                                | 173/265 |  65.28%
    4. Tempura (Tempura)                                  | 127/265 |  47.92%
    5. Okonomiyaki (Japanese Pancake)                     |  99/265 |  37.36%
    6. Khác                                               |   1/265 |   0.38%
    7. sashimi                                            |   1/265 |   0.38%
    8. Cà ri Nhật đỉnh                                    |   1/265 |   0.38%
    9. Ko                                                 |   1/265 |   0.38%
   10. Kẹo kitkat                                         |   1/265 |   0.38%

📝 MẪU GIÁ TRỊ (5 giá trị đầu tiên):
   1. Sushi (Sushi), Ramen (Ramen), Tempura (Tempura), Okonomiyaki (Japanese Pancake), Udon (Udon noodles)...
   2. Sushi (Sushi), Ramen (Ramen), Udon (Udon noodles)...
   3. Sushi (Sushi)...
   4. Okonomiyaki (Japanese Pancake)...
   5. Ramen (Ramen)...

📏 Thống kê độ dài giá trị:
   - Độ dài trung bình: 55.8 ký tự
   - Độ dài ngắn nhất: 2 ký tự
   - Độ dài dài nhất: 129 ký tự

================================================================================
🍽️ NHẬT BẢN
================================================================================
Cột: Bạn thích những món ăn Nhật Bản nào sau đây? (Which Japanese dishes do you like?)

📈 Thống kê:
   - Số giá trị không null: 269/271 (99.3%)
   - Số giá trị null: 2/271 (0.7%)

📋 Phân tích giá trị:
   - Số bản ghi có dữ liệu: 269
   - Số tổ hợp giá trị duy nhất: 34
   - Tổng số món ăn (sau khi tách): 907
   - Số món ăn duy nhất: 11

🏆 TOP 10 MÓN ĂN PHỔ BIẾN NHẤT:
   ----------------------------------------------------------------------
    1. Gà rán Hàn Quốc (Korean Fried Chicken)             | 213/269 |  79.18%
    2. Cơm trộn Bibimbap (Bibimbap)                       | 209/269 |  77.70%
    3. Bánh gạo cay Tteokbokki (Tteokbokki)               | 194/269 |  72.12%
    4. Kimchi (Kimchi)                                    | 181/269 |  67.29%
    5. Bulgogi (Grilled Beef)                             | 104/269 |  38.66%
    6. Khác                                               |   1/269 |   0.37%
    7. Lòng nướng                                         |   1/269 |   0.37%
    8. Ko                                                 |   1/269 |   0.37%
    9. Bánh ngọt                                          |   1/269 |   0.37%
   10. mì tương đen                                       |   1/269 |   0.37%

📝 MẪU GIÁ TRỊ (5 giá trị đầu tiên):
   1. Kimchi (Kimchi), Cơm trộn Bibimbap (Bibimbap), Bulgogi (Grilled Beef), Bánh gạo cay Tteokbokki (Tteo...
   2. Kimchi (Kimchi), Cơm trộn Bibimbap (Bibimbap), Bánh gạo cay Tteokbokki (Tteokbokki), Gà rán Hàn Quốc...
   3. Kimchi (Kimchi)...
   4. Gà rán Hàn Quốc (Korean Fried Chicken)...
   5. Cơm trộn Bibimbap (Bibimbap)...

📏 Thống kê độ dài giá trị:
   - Độ dài trung bình: 101.4 ký tự
   - Độ dài ngắn nhất: 2 ký tự
   - Độ dài dài nhất: 168 ký tự

================================================================================
🍽️ HÀN QUỐC
================================================================================
Cột: Bạn thích những món ăn Hàn Quốc nào sau đây? (Which Korean dishes do you like?)

📈 Thống kê:
   - Số giá trị không null: 253/271 (93.4%)
   - Số giá trị null: 18/271 (6.6%)

📋 Phân tích giá trị:
   - Số bản ghi có dữ liệu: 253
   - Số tổ hợp giá trị duy nhất: 13
   - Tổng số món ăn (sau khi tách): 594
   - Số món ăn duy nhất: 7

🏆 TOP 10 MÓN ĂN PHỔ BIẾN NHẤT:
   ----------------------------------------------------------------------
    1. BBQ Sườn nướng (Barbecue Ribs)                     | 212/253 |  83.79%
    2. Hamburger (Hamburger)                              | 197/253 |  77.87%
    3. Hot Dog (Hot Dog)                                  | 181/253 |  71.54%
    4. Ko                                                 |   1/253 |   0.40%
    5. Gà cosco                                           |   1/253 |   0.40%
    6. gà rán                                             |   1/253 |   0.40%
    7. Món ăn ngon là được                                |   1/253 |   0.40%

📝 MẪU GIÁ TRỊ (5 giá trị đầu tiên):
   1. Hamburger (Hamburger), Hot Dog (Hot Dog), BBQ Sườn nướng (Barbecue Ribs)...
   2. BBQ Sườn nướng (Barbecue Ribs)...
   3. BBQ Sườn nướng (Barbecue Ribs)...
   4. Hamburger (Hamburger), BBQ Sườn nướng (Barbecue Ribs)...
   5. BBQ Sườn nướng (Barbecue Ribs)...

📏 Thống kê độ dài giá trị:
   - Độ dài trung bình: 56.5 ký tự
   - Độ dài ngắn nhất: 2 ký tự
   - Độ dài dài nhất: 94 ký tự

================================================================================
🍽️ MỸ
================================================================================
Cột: Bạn thích những món ăn Mỹ? (Which American dishes do you like?)

📈 Thống kê:
   - Số giá trị không null: 120/271 (44.3%)
   - Số giá trị null: 151/271 (55.7%)

📋 Phân tích giá trị:
   - Số bản ghi có dữ liệu: 120
   - Số tổ hợp giá trị duy nhất: 87
   - Tổng số món ăn (sau khi tách): 157
   - Số món ăn duy nhất: 112

🏆 TOP 10 MÓN ĂN PHỔ BIẾN NHẤT:
   ----------------------------------------------------------------------
    1. Bún bò                                             |  11/120 |   9.17%
    2. Không                                              |   9/120 |   7.50%
    3. không                                              |   6/120 |   5.00%
    4. Không có                                           |   5/120 |   4.17%
    5. không có                                           |   4/120 |   3.33%
    6. Cơm sườn                                           |   3/120 |   2.50%
    7. Bún Bò                                             |   3/120 |   2.50%
    8. bún bò                                             |   3/120 |   2.50%
    9. ko                                                 |   3/120 |   2.50%
   10. Bún đậu mắm tôm                                    |   2/120 |   1.67%

📝 MẪU GIÁ TRỊ (5 giá trị đầu tiên):
   1. không...
   2. Có nhiều, liệt kê ko hết...
   3. Bún đậu mắm tôm...
   4. Panna cotta...
   5. Bì Bún (Việt Nam)...

📏 Thống kê độ dài giá trị:
   - Độ dài trung bình: 14.8 ký tự
   - Độ dài ngắn nhất: 2 ký tự
   - Độ dài dài nhất: 154 ký tự

In [29]:
# 🔗 Logic: Lấy món ăn dựa trên quốc gia yêu thích và tính tỷ lệ
print("🔗 LOGIC MAPPING: QUỐC GIA YÊU THÍCH → MÓN ĂN TƯƠNG ỨNG + TỶ LỆ")
print("="*80)

# Mapping giữa quốc gia yêu thích và cột món ăn tương ứng
COUNTRY_TO_DISH_COLUMN = {
    # Vietnamese
    'Vietnamese': 'Bạn thích những món ăn Việt Nam nào sau đây? (Which Vietnamese dishes do you like?)',
    'Việt Nam': 'Bạn thích những món ăn Việt Nam nào sau đây? (Which Vietnamese dishes do you like?)',
    'Việt Nam (Vietnamese)': 'Bạn thích những món ăn Việt Nam nào sau đây? (Which Vietnamese dishes do you like?)',
    
    # Thai
    'Thai': 'Bạn thích những món ăn Thái Lan nào sau đây? (Which Thai dishes do you like?)',
    'Thái Lan': 'Bạn thích những món ăn Thái Lan nào sau đây? (Which Thai dishes do you like?)',
    'Thái Lan (Thai)': 'Bạn thích những món ăn Thái Lan nào sau đây? (Which Thai dishes do you like?)',
    
    # Chinese
    'Chinese': 'Bạn thích những món ăn Trung Quốc nào sau đây? (Which Chinese dishes do you like?)  ',
    'Trung Quốc': 'Bạn thích những món ăn Trung Quốc nào sau đây? (Which Chinese dishes do you like?)  ',
    'Trung Quốc (Chinese)': 'Bạn thích những món ăn Trung Quốc nào sau đây? (Which Chinese dishes do you like?)  ',
    
    # French
    'French': 'Bạn thích những món ăn Pháp nào sau đây? (Which French dishes do you like?)',
    'Pháp': 'Bạn thích những món ăn Pháp nào sau đây? (Which French dishes do you like?)',
    'Pháp (French)': 'Bạn thích những món ăn Pháp nào sau đây? (Which French dishes do you like?)',
    
    # Indian
    'Indian': 'Bạn thích những món ăn Ấn Độ nào sau đây? (Which Indian dishes do you like?)  ',
    'Ấn Độ': 'Bạn thích những món ăn Ấn Độ nào sau đây? (Which Indian dishes do you like?)  ',
    'Ấn Độ (Indian)': 'Bạn thích những món ăn Ấn Độ nào sau đây? (Which Indian dishes do you like?)  ',
    
    # Italian
    'Italian': 'Bạn thích những món ăn Ý nào sau đây? (Which Italian dishes do you like?)  ',
    'Ý': 'Bạn thích những món ăn Ý nào sau đây? (Which Italian dishes do you like?)  ',
    'Ý (Italian)': 'Bạn thích những món ăn Ý nào sau đây? (Which Italian dishes do you like?)  ',
    
    # Japanese
    'Japanese': 'Bạn thích những món ăn Nhật Bản nào sau đây? (Which Japanese dishes do you like?)',
    'Nhật Bản': 'Bạn thích những món ăn Nhật Bản nào sau đây? (Which Japanese dishes do you like?)',
    'Nhật Bản (Japanese)': 'Bạn thích những món ăn Nhật Bản nào sau đây? (Which Japanese dishes do you like?)',
    
    # Korean
    'Korean': 'Bạn thích những món ăn Hàn Quốc nào sau đây? (Which Korean dishes do you like?)',
    'Hàn Quốc': 'Bạn thích những món ăn Hàn Quốc nào sau đây? (Which Korean dishes do you like?)',
    'Hàn Quốc (Korean)': 'Bạn thích những món ăn Hàn Quốc nào sau đây? (Which Korean dishes do you like?)',
    
    # American
    'American': 'Bạn thích những món ăn Mỹ? (Which American dishes do you like?)',
    'Mỹ': 'Bạn thích những món ăn Mỹ? (Which American dishes do you like?)',
    'Mỹ (American)': 'Bạn thích những món ăn Mỹ? (Which American dishes do you like?)',
}

# Tìm tên cột quốc gia từ DataFrame (tránh lỗi ký tự đặc biệt)
country_col = None
for col in df.columns:
    if 'quốc gia' in col.lower() and 'cuisine' in col.lower():
        country_col = col
        break

if country_col is None:
    # Fallback: tìm cột có chứa "quốc gia"
    matching_cols = [col for col in df.columns if 'quốc gia' in col.lower()]
    if matching_cols:
        country_col = matching_cols[0]

print(f"✅ Đã tìm thấy cột: '{country_col}'")

# Hàm phân tích tỷ lệ món ăn cho một quốc gia
def analyze_dish_preferences_by_country(country_name, country_keywords):
    """
    Phân tích tỷ lệ món ăn yêu thích cho một quốc gia cụ thể
    
    Args:
        country_name: Tên quốc gia để hiển thị (ví dụ: "Việt Nam")
        country_keywords: List các từ khóa để tìm (ví dụ: ["Vietnamese", "Việt Nam"])
    
    Returns:
        DataFrame với thống kê món ăn và tỷ lệ
    """
    if country_col not in df.columns:
        return None
    
    # Tìm các user chọn quốc gia này
    pattern = '|'.join(country_keywords)
    users_with_country = df[df[country_col].str.contains(pattern, case=False, na=False)]
    total_users = len(users_with_country)
    
    if total_users == 0:
        print(f"   ❌ Không tìm thấy user nào yêu thích {country_name}")
        return None
    
    print(f"\n📍 {country_name.upper()}:")
    print(f"   - Tổng số user chọn quốc gia này: {total_users}")
    
    # Lấy cột món ăn tương ứng - ưu tiên tìm trực tiếp từ tên quốc gia
    dish_col = None
    
    # Cách 1: Tìm trực tiếp từ DataFrame dựa trên tên quốc gia (chính xác nhất)
    country_name_lower = country_name.lower()
    for col in df.columns:
        if 'món ăn' in col.lower() and country_name_lower in col.lower():
            dish_col = col
            print(f"   ✅ Tìm thấy cột món ăn trực tiếp: '{dish_col[:60]}...'")
            break
    
    # Cách 2: Nếu không tìm thấy, dùng mapping dictionary
    if not dish_col or dish_col not in df.columns:
        for keyword in country_keywords:
            dish_col = COUNTRY_TO_DISH_COLUMN.get(keyword)
            if dish_col and dish_col in df.columns:
                print(f"   ✅ Tìm thấy cột món ăn từ mapping (keyword '{keyword}'): '{dish_col[:60]}...'")
                break
    
    # Xác minh lại cột có đúng không
    if dish_col and dish_col in df.columns:
        # Kiểm tra tên cột có chứa tên quốc gia không
        if country_name_lower not in dish_col.lower():
            print(f"   ⚠️ CẢNH BÁO: Cột món ăn có vẻ không khớp với '{country_name}'!")
            print(f"   - Tên cột: '{dish_col}'")
            # Thử tìm lại
            for col in df.columns:
                if 'món ăn' in col.lower() and country_name_lower in col.lower():
                    dish_col = col
                    print(f"   ✅ Đã sửa lại cột đúng: '{dish_col[:60]}...'")
                    break
    
    if not dish_col or dish_col not in df.columns:
        print(f"   ❌ Không tìm thấy cột món ăn tương ứng cho '{country_name}'")
        print(f"   🔍 Đã thử keywords: {country_keywords}")
        return None
    
    # Lấy món ăn của các user chọn quốc gia này
    dishes_data = users_with_country[dish_col].dropna()
    users_with_dishes = len(dishes_data)
    
    print(f"   - Số user có dữ liệu món ăn: {users_with_dishes}/{total_users} ({users_with_dishes/total_users*100:.1f}%)")
    
    # Phân tích từng món ăn
    from collections import Counter
    all_dishes = []
    
    for dish_str in dishes_data:
        if pd.notna(dish_str):
            # Tách các món ăn (phân cách bằng dấu phẩy)
            dishes = [d.strip() for d in str(dish_str).split(',') if d.strip()]
            all_dishes.extend(dishes)
    
    # Đếm số lần xuất hiện của mỗi món
    dish_counts = Counter(all_dishes)
    
    # Tạo DataFrame kết quả
    results = []
    for dish, count in dish_counts.most_common():
        percentage = (count / total_users) * 100
        results.append({
            'Món ăn (Dish)': dish,
            'Số user thích (Users)': count,
            'Tổng user chọn quốc gia (Total)': total_users,
            'Tỷ lệ (%)': f"{percentage:.2f}%",
            'Tỷ lệ (số)': percentage
        })
    
    result_df = pd.DataFrame(results)
    
    print(f"\n   📊 TOP 10 MÓN ĂN PHỔ BIẾN NHẤT:")
    print("   " + "-" * 70)
    for idx, row in result_df.head(10).iterrows():
        print(f"   {idx+1:2d}. {row['Món ăn (Dish)']:<40} | {row['Số user thích (Users)']:>3}/{row['Tổng user chọn quốc gia (Total)']:<3} | {row['Tỷ lệ (%)']:>7}")
    
    return result_df

# Kiểm tra và hiển thị mẫu giá trị
if country_col and country_col in df.columns:
    print(f"\n📋 Mẫu giá trị từ cột '{country_col}':")
    sample_values = df[country_col].head(3)
    for idx, val in sample_values.items():
        print(f"  - {val}")
else:
    print(f"\n❌ Không tìm thấy cột quốc gia!")

# Ví dụ 1: Phân tích món ăn Việt Nam
print("\n" + "="*80)
print("📌 VÍ DỤ 1: PHÂN TÍCH MÓN ĂN VIỆT NAM")
print("="*80)

vietnamese_stats = analyze_dish_preferences_by_country(
    "Việt Nam", 
    ["Vietnamese", "Việt Nam"]
)

# Hiển thị kết quả nếu có
if vietnamese_stats is not None:
    print(f"\n✅ Phân tích thành công! Tổng số món ăn: {len(vietnamese_stats)}")
    print("\n📊 DataFrame kết quả:")
    print(vietnamese_stats.head(10))
else:
    print("\n❌ Không có kết quả trả về. Kiểm tra lại logic.")

🔗 LOGIC MAPPING: QUỐC GIA YÊU THÍCH → MÓN ĂN TƯƠNG ỨNG + TỶ LỆ
================================================================================
✅ Đã tìm thấy cột: ' Bạn yêu thích món ăn của quốc gia nào? (Which country’s cuisine do you like?)'

📋 Mẫu giá trị từ cột ' Bạn yêu thích món ăn của quốc gia nào? (Which country’s cuisine do you like?)':
  - Phở (Pho), Bánh mì (Banh Mi), Bún chả (Grilled Pork with Vermicelli), Gỏi cuốn (Spring Rolls), Bánh xèo (Vietnamese Pancake), Khác
  - Phở (Pho), Bánh mì (Banh Mi), Bún chả (Grilled Pork with Vermicelli), Gỏi cuốn (Spring Rolls), Bánh xèo (Vietnamese Pancake)
  - Phở (Pho)

================================================================================
📌 VÍ DỤ 1: PHÂN TÍCH MÓN ĂN VIỆT NAM
================================================================================

📍 VIỆT NAM:
   - Tổng số user chọn quốc gia này: 150
   ✅ Tìm thấy cột món ăn trực tiếp: 'Bạn thích những món ăn Việt Nam nào sau đây? (Which Vietname...'
   - Số user có dữ liệu món ăn: 143/150 (95.3%)

   📊 TOP 10 MÓN ĂN PHỔ BIẾN NHẤT:
   ----------------------------------------------------------------------
    1. Xôi xoài (Mango Sticky Rice)             |  89/150 |  59.33%
    2. Canh Tom Yum (Tom Yum Soup)              |  88/150 |  58.67%
    3. Gỏi đu đủ Som Tum (Papaya Salad)         |  77/150 |  51.33%
    4. Pad Thái (Pad Thai)                      |  67/150 |  44.67%
    5. Cà ri xanh (Green Curry)                 |  39/150 |  26.00%
    6. Cơm rang dứa                             |   1/150 |   0.67%
    7. Chưa ăn món thái nào                     |   1/150 |   0.67%
    8. Bánh mì chuối                            |   1/150 |   0.67%
    9. Mỳ Ý                                     |   1/150 |   0.67%
   10. Tôi không thích món thái                 |   1/150 |   0.67%

✅ Phân tích thành công! Tổng số món ăn: 12

📊 DataFrame kết quả:
                      Món ăn (Dish)  Số user thích (Users)  \
0      Xôi xoài (Mango Sticky Rice)                     89
1       Canh Tom Yum (Tom Yum Soup)                     88
2  Gỏi đu đủ Som Tum (Papaya Salad)                     77
3               Pad Thái (Pad Thai)                     67
4          Cà ri xanh (Green Curry)                     39
5                      Cơm rang dứa                      1
6              Chưa ăn món thái nào                      1
7                     Bánh mì chuối                      1
8                              Mỳ Ý                      1
9          Tôi không thích món thái                      1

   Tổng user chọn quốc gia (Total) Tỷ lệ (%)  Tỷ lệ (số)
0                              150    59.33%   59.333333
1                              150    58.67%   58.666667
2                              150    51.33%   51.333333
3                              150    44.67%   44.666667
4                              150    26.00%   26.000000
5                              150     0.67%    0.666667
6                              150     0.67%    0.666667
7                              150     0.67%    0.666667
8                              150     0.67%    0.666667
9                              150     0.67%    0.666667

In [18]:
# 📊 Tạo bảng tổng hợp: Quốc gia → Số lượng user → Món ăn phổ biến
print("📊 BẢNG TỔNG HỢP: QUỐC GIA YÊU THÍCH VÀ MÓN ĂN TƯƠNG ỨNG")
print("="*80)

country_col = ' Bạn yêu thích món ăn của quốc gia nào?'

if country_col in df.columns:
    summary_data = []
    
    # Danh sách các quốc gia và cột món ăn tương ứng
    countries_mapping = {
        'Vietnamese': {
            'name_vi': 'Việt Nam',
            'dish_col': 'Bạn thích những món ăn Việt Nam nào sau đây? (Which Vietnamese dishes do you like?)'
        },
        'Thai': {
            'name_vi': 'Thái Lan',
            'dish_col': 'Bạn thích những món ăn Thái Lan nào sau đây? (Which Thai dishes do you like?)'
        },
        'Chinese': {
            'name_vi': 'Trung Quốc',
            'dish_col': 'Bạn thích những món ăn Trung Quốc nào sau đây? (Which Chinese dishes do you like?)  '
        },
        'French': {
            'name_vi': 'Pháp',
            'dish_col': 'Bạn thích những món ăn Pháp nào sau đây? (Which French dishes do you like?)'
        },
        'Indian': {
            'name_vi': 'Ấn Độ',
            'dish_col': 'Bạn thích những món ăn Ấn Độ nào sau đây? (Which Indian dishes do you like?)  '
        },
        'Italian': {
            'name_vi': 'Ý',
            'dish_col': 'Bạn thích những món ăn Ý nào sau đây? (Which Italian dishes do you like?)  '
        },
        'Japanese': {
            'name_vi': 'Nhật Bản',
            'dish_col': 'Bạn thích những món ăn Nhật Bản nào sau đây? (Which Japanese dishes do you like?)'
        },
        'Korean': {
            'name_vi': 'Hàn Quốc',
            'dish_col': 'Bạn thích những món ăn Hàn Quốc nào sau đây? (Which Korean dishes do you like?)'
        },
        'American': {
            'name_vi': 'Mỹ',
            'dish_col': 'Bạn thích những món ăn Mỹ? (Which American dishes do you like?)'
        }
    }
    
    for country_key, info in countries_mapping.items():
        dish_col = info['dish_col']
        name_vi = info['name_vi']
        
        # Đếm số user chọn quốc gia này
        users_with_country = df[df[country_col].str.contains(country_key, case=False, na=False)]
        num_users = len(users_with_country)
        
        # Đếm số user có món ăn tương ứng
        if dish_col in df.columns:
            users_with_dishes = df[dish_col].notna().sum()
            
            # Lấy món ăn của những user chọn quốc gia này
            if num_users > 0:
                dishes_list = users_with_country[dish_col].dropna().tolist()
                # Đếm món ăn phổ biến (có thể có nhiều món trong một chuỗi)
                all_dishes = []
                for dish_str in dishes_list:
                    if pd.notna(dish_str):
                        # Tách các món ăn (phân cách bằng dấu phẩy)
                        dishes = [d.strip() for d in str(dish_str).split(',')]
                        all_dishes.extend(dishes)
                
                from collections import Counter
                dish_counts = Counter(all_dishes)
                top_dishes = dish_counts.most_common(3)
                
                summary_data.append({
                    'Quốc gia (Country)': f"{name_vi} ({country_key})",
                    'Số user chọn (Users)': num_users,
                    'Số user có món ăn (Users with dishes)': users_with_dishes,
                    'Món ăn phổ biến nhất (Top dishes)': ', '.join([f"{dish} ({count})" for dish, count in top_dishes])
                })
    
    summary_df = pd.DataFrame(summary_data)
    print("\n")
    print(summary_df.to_string(index=False))
    
    print("\n" + "="*80)
    print("✅ LOGIC HOÀN CHỈNH:")
    print("   - Nếu user chọn quốc gia yêu thích → Lấy món ăn từ cột tương ứng")
    print("   - Ví dụ: User chọn 'Vietnamese' → Lấy từ cột 'Bạn thích những món ăn Việt Nam nào sau đây?'")

📊 BẢNG TỔNG HỢP: QUỐC GIA YÊU THÍCH VÀ MÓN ĂN TƯƠNG ỨNG
================================================================================

📊 BẢNG TỔNG HỢP CHI TIẾT: TỶ LỆ MÓN ĂN THEO QUỐC GIA
================================================================================

In [9]:
# 📝 Tạo bảng tóm tắt cấu trúc database
print("📝 TÓM TẮT CẤU TRÚC DATABASE:")
print("="*80)

database_structure = {
    "Tên bảng": "users",
    "Số lượng bản ghi": len(df),
    "Số lượng cột": len(df.columns),
    "Các nhóm thông tin": {
        "Thông tin cá nhân": [
            "Dấu thời gian",
            "Giới tính (Gender)",
            "Độ tuổi (Age)",
            "Họ và tên (Full Name)",
            "Địa chỉ email"
        ],
        "Thông tin sức khỏe": [
            "Hạn chế chế độ ăn (Dietary restrictions)",
            "Dị ứng thực phẩm (Food allergies)"
        ],
        "Thông tin nấu ăn": [
            "Loại bữa ăn quan tâm (Meal types)",
            "Mức độ kỹ năng nấu ăn (Cooking skill level)",
            "Thời gian nấu ăn (Cooking time)"
        ],
        "Sở thích ẩm thực": [
            "Quốc gia yêu thích (Favorite countries)",
            "Món ăn Việt Nam yêu thích",
            "Món ăn Thái Lan yêu thích",
            "Món ăn Trung Quốc yêu thích",
            "Món ăn Pháp yêu thích",
            "Món ăn Ấn Độ yêu thích",
            "Món ăn Ý yêu thích",
            "Món ăn Nhật Bản yêu thích",
            "Món ăn Hàn Quốc yêu thích",
            "Món ăn Mỹ yêu thích",
            "Món ăn khác chưa được đề cập"
        ]
    }
}

import json
print(json.dumps(database_structure, indent=2, ensure_ascii=False))

📝 TÓM TẮT CẤU TRÚC DATABASE:
================================================================================
{
  "Tên bảng": "users",
  "Số lượng bản ghi": 271,
  "Số lượng cột": 21,
  "Các nhóm thông tin": {
    "Thông tin cá nhân": [
      "Dấu thời gian",
      "Giới tính (Gender)",
      "Độ tuổi (Age)",
      "Họ và tên (Full Name)",
      "Địa chỉ email"
    ],
    "Thông tin sức khỏe": [
      "Hạn chế chế độ ăn (Dietary restrictions)",
      "Dị ứng thực phẩm (Food allergies)"
    ],
    "Thông tin nấu ăn": [
      "Loại bữa ăn quan tâm (Meal types)",
      "Mức độ kỹ năng nấu ăn (Cooking skill level)",
      "Thời gian nấu ăn (Cooking time)"
    ],
    "Sở thích ẩm thực": [
      "Quốc gia yêu thích (Favorite countries)",
      "Món ăn Việt Nam yêu thích",
      "Món ăn Thái Lan yêu thích",
      "Món ăn Trung Quốc yêu thích",
      "Món ăn Pháp yêu thích",
      "Món ăn Ấn Độ yêu thích",
      "Món ăn Ý yêu thích",
      "Món ăn Nhật Bản yêu thích",
      "Món ăn Hàn Quốc yêu thích",
      "Món ăn Mỹ yêu thích",
      "Món ăn khác chưa được đề cập"
    ]
  }
}

🧹 CLEAN DATA: LOẠI BỎ TIẾNG VIỆT, CHỈ GIỮ TIẾNG ANH
================================================================================
📂 Đã đọc file: C:\Users\ThaoMuy\Downloads\Recommend_System\backend\data\users\users.csv
📊 Số dòng: 271
📊 Số cột: 21

🔄 Đang clean data...
   ✅ Đã clean cột: Giới tính (Gender) ...
   ✅ Đã clean cột:   Độ tuổi (Age)  ...
   ✅ Đã clean cột:   Bạn có hạn chế chế độ ăn nào không? (Do you have any dieta...
   ✅ Đã clean cột:   Bạn có dị ứng với thực phẩm nào không? (Do you have any fo...
   ✅ Đã clean cột: Bạn thường quan tâm đến loại bữa ăn nào? (Which type of meal...
   ✅ Đã clean cột: Mức độ kỹ năng nấu ăn của bạn là gì? (Your cooking skill lev...
   ✅ Đã clean cột: Bạn có bao nhiêu thời gian để nấu ăn trung bình? (How much t...
   ✅ Đã clean cột:  Bạn yêu thích món ăn của quốc gia nào? (Which country’s cui...
   ✅ Đã clean cột: Bạn thích những món ăn Việt Nam nào sau đây? (Which Vietname...
   ✅ Đã clean cột: Bạn thích những món ăn Thái Lan nào sau đây? (Which Thai dis...
   ✅ Đã clean cột: Bạn thích những món ăn Trung Quốc nào sau đây? (Which Chines...
   ✅ Đã clean cột: Bạn thích những món ăn Pháp nào sau đây? (Which French dishe...
   ✅ Đã clean cột: Bạn thích những món ăn Ấn Độ nào sau đây? (Which Indian dish...
   ✅ Đã clean cột: Bạn thích những món ăn Ý nào sau đây? (Which Italian dishes ...
   ✅ Đã clean cột: Bạn thích những món ăn Nhật Bản nào sau đây? (Which Japanese...
   ✅ Đã clean cột: Bạn thích những món ăn Hàn Quốc nào sau đây? (Which Korean d...
   ✅ Đã clean cột: Bạn thích những món ăn Mỹ? (Which American dishes do you lik...
   ✅ Đã clean cột: Có món ăn nào bạn thích mà chưa được đề cập trong danh sách ...

✅ Đã clean 18 cột
📌 Giữ nguyên các cột: ['Họ và tên (Full Name)', 'Địa chỉ email', 'Dấu thời gian']

📋 MẪU DỮ LIỆU SAU KHI CLEAN:
================================================================================
                    Dấu thời gian Giới tính (Gender)    Độ tuổi (Age)    \
03/10/2025 21:34:22    Nam (Male)             18 – 24         Allergies
03/10/2025 23:30:38    Nam (Male)             25 – 34         Low sugar
04/10/2025 0:00:53    Nữ (Female)             18 – 30   No restrictions

                      Bạn có hạn chế chế độ ăn nào không? (Do you have any dietary restrictions?)    \
03/10/2025 21:34:22                                            Seafood
03/10/2025 23:30:38                                       No allergies
04/10/2025 0:00:53                                        No allergies

                      Bạn có dị ứng với thực phẩm nào không? (Do you have any food allergies?)    \
03/10/2025 21:34:22  Breakfast, Lunch, Dinner, Appetizer, Dessert, ...
03/10/2025 23:30:38                           Breakfast, Lunch, Dinner
04/10/2025 0:00:53                                       Lunch, Dinner

                    Bạn thường quan tâm đến loại bữa ăn nào? (Which type of meal do you usually care about?)  \
03/10/2025 21:34:22                                           Beginner
03/10/2025 23:30:38                                           Beginner
04/10/2025 0:00:53                                        Intermediate

                    Mức độ kỹ năng nấu ăn của bạn là gì? (Your cooking skill level)  \
03/10/2025 21:34:22                                       < 15 minutes
03/10/2025 23:30:38                                    30 – 60 minutes
04/10/2025 0:00:53                                     30 – 60 minutes

                    Bạn có bao nhiêu thời gian để nấu ăn trung bình? (How much time do you usually have to cook?)  \
03/10/2025 21:34:22  Vietnamese, Chinese, Italian, Japanese, Korean...
03/10/2025 23:30:38                       Vietnamese, Japanese, Korean
04/10/2025 0:00:53                                          Vietnamese

                     Bạn yêu thích món ăn của quốc gia nào? (Which country’s cuisine do you like?)  \
03/10/2025 21:34:22  Pho, Banh Mi, Grilled Pork with Vermicelli, Sp...
03/10/2025 23:30:38  Pho, Banh Mi, Grilled Pork with Vermicelli, Sp...
04/10/2025 0:00:53                                                 Pho

                    Bạn thích những món ăn Việt Nam nào sau đây? (Which Vietnamese dishes do you like?)  \
03/10/2025 21:34:22                                                NaN
03/10/2025 23:30:38  Pad Thai, Tom Yum Soup, Green Curry, Papaya Sa...
04/10/2025 0:00:53                                            Pad Thai

                     ...  \
03/10/2025 21:34:22  ...
03/10/2025 23:30:38  ...
04/10/2025 0:00:53   ...

                    Bạn thích những món ăn Trung Quốc nào sau đây? (Which Chinese dishes do you like?)    \
03/10/2025 21:34:22     Croissant, Baguette, Crème Brûlée, Ratatouille
03/10/2025 23:30:38                                          Croissant
04/10/2025 0:00:53                                            Baguette

                    Bạn thích những món ăn Pháp nào sau đây? (Which French dishes do you like?)  \
03/10/2025 21:34:22  Biryani, Butter Chicken, Chicken Tikka Masala,...
03/10/2025 23:30:38                               Chicken Tikka Masala
04/10/2025 0:00:53                                              Samosa

                    Bạn thích những món ăn Ấn Độ nào sau đây? (Which Indian dishes do you like?)    \
03/10/2025 21:34:22  Pizza, Spaghetti Carbonara, Lasagna, Tiramisu,...
03/10/2025 23:30:38               Pizza, Spaghetti Carbonara, Tiramisu
04/10/2025 0:00:53                                 Spaghetti Carbonara

                    Bạn thích những món ăn Ý nào sau đây? (Which Italian dishes do you like?)    \
03/10/2025 21:34:22  Sushi, Ramen, Tempura, Japanese Pancake, Udon ...
03/10/2025 23:30:38                         Sushi, Ramen, Udon noodles
04/10/2025 0:00:53                                               Sushi

                    Bạn thích những món ăn Nhật Bản nào sau đây? (Which Japanese dishes do you like?)  \
03/10/2025 21:34:22  Kimchi, Bibimbap, Grilled Beef, Tteokbokki, Ko...
03/10/2025 23:30:38  Kimchi, Bibimbap, Tteokbokki, Korean Fried Chi...
04/10/2025 0:00:53                                              Kimchi

                    Bạn thích những món ăn Hàn Quốc nào sau đây? (Which Korean dishes do you like?)  \
03/10/2025 21:34:22                                                NaN
03/10/2025 23:30:38                                                NaN
04/10/2025 0:00:53                                                 NaN

                    Bạn thích những món ăn Mỹ? (Which American dishes do you like?)  \
03/10/2025 21:34:22                                                NaN
03/10/2025 23:30:38                                                NaN
04/10/2025 0:00:53                                                 NaN

                    Có món ăn nào bạn thích mà chưa được đề cập trong danh sách trên không? (nếu có)\r\nIs there any dish you like that was not mentioned in the list above?  \
03/10/2025 21:34:22                                                NaN
03/10/2025 23:30:38                                                NaN
04/10/2025 0:00:53                                                 NaN

                    Họ và tên (Full Name) Địa chỉ email
03/10/2025 21:34:22                   NaN           NaN
03/10/2025 23:30:38                   NaN           NaN
04/10/2025 0:00:53                    NaN           NaN

[3 rows x 21 columns]

💾 Đã lưu file cleaned: C:\Users\ThaoMuy\Downloads\Recommend_System\backend\data\users\users_cleaned.csv

📊 SO SÁNH TRƯỚC VÀ SAU:
================================================================================

🔍 Cột mẫu: Bạn thích những món ăn Việt Nam nào sau đây? (Which Vietname...

📝 TRƯỚC (Original):
   03/10/2025 23:30:38: Pad Thái (Pad Thai), Canh Tom Yum (Tom Yum Soup), Cà ri xanh (Green Curry), Gỏi đu đủ Som Tum (Papay
   04/10/2025 0:00:53: Pad Thái (Pad Thai)
   04/10/2025 0:05:58: Gỏi đu đủ Som Tum (Papaya Salad)

📝 SAU (Cleaned):
   03/10/2025 23:30:38: Pad Thai, Tom Yum Soup, Green Curry, Papaya Salad, Mango Sticky Rice
   04/10/2025 0:00:53: Pad Thai
   04/10/2025 0:05:58: Papaya Salad

✅ HOÀN THÀNH CLEAN DATA!

In [10]:
# 📊 Tạo DataFrame tóm tắt các cột
print("📊 BẢNG TÓM TẮT CÁC CỘT:")
print("="*80)

summary_data = []
for col in df.columns:
    summary_data.append({
        "Tên cột": col,
        "Kiểu dữ liệu": str(df[col].dtype),
        "Số giá trị không null": df[col].notna().sum(),
        "Số giá trị null": df[col].isna().sum(),
        "% Không null": f"{df[col].notna().sum()/len(df)*100:.1f}%",
        "Số giá trị duy nhất": df[col].nunique()
    })

summary_df = pd.DataFrame(summary_data)
summary_df

📊 BẢNG TÓM TẮT CÁC CỘT:
================================================================================

,Tên cột,Kiểu dữ liệu,Số giá trị không null,Số giá trị null,% Không null,Số giá trị duy nhất
0,Dấu thời gian,object,271,0,100.0%,2
1,Giới tính (Gender),object,271,0,100.0%,6
2,Độ tuổi (Age),object,271,0,100.0%,25
3,Bạn có hạn chế chế độ ăn nào không? (Do you ...,object,271,0,100.0%,15
4,Bạn có dị ứng với thực phẩm nào không? (Do y...,object,271,0,100.0%,50
5,Bạn thường quan tâm đến loại bữa ăn nào? (Whic...,object,269,2,99.3%,3
6,Mức độ kỹ năng nấu ăn của bạn là gì? (Your coo...,object,271,0,100.0%,10
7,Bạn có bao nhiêu thời gian để nấu ăn trung bìn...,object,271,0,100.0%,53
8,Bạn yêu thích món ăn của quốc gia nào? (Which...,object,271,0,100.0%,55
9,Bạn thích những món ăn Việt Nam nào sau đây? (...,object,259,12,95.6%,41
10,Bạn thích những món ăn Thái Lan nào sau đây? (...,object,265,6,97.8%,38
11,Bạn thích những món ăn Trung Quốc nào sau đây?...,object,262,9,96.7%,27
12,Bạn thích những món ăn Pháp nào sau đây? (Whic...,object,235,36,86.7%,42
13,Bạn thích những món ăn Ấn Độ nào sau đây? (Whi...,object,269,2,99.3%,19
14,Bạn thích những món ăn Ý nào sau đây? (Which I...,object,265,6,97.8%,39
15,Bạn thích những món ăn Nhật Bản nào sau đây? (...,object,269,2,99.3%,34
16,Bạn thích những món ăn Hàn Quốc nào sau đây? (...,object,253,18,93.4%,13
17,Bạn thích những món ăn Mỹ? (Which American dis...,object,120,151,44.3%,93
18,Có món ăn nào bạn thích mà chưa được đề cập tr...,object,211,60,77.9%,209
19,Họ và tên (Full Name),object,211,60,77.9%,208
20,Địa chỉ email,float64,0,271,0.0%,0

## 📋 KẾT LUẬN VỀ CẤU TRÚC DATABASE

File `users.csv` chứa dữ liệu khảo sát người dùng với các thông tin sau:

### 🗂️ Cấu trúc chính:
1. **Thông tin cá nhân**: Timestamp, Giới tính, Độ tuổi, Họ tên, Email
2. **Thông tin sức khỏe**: Hạn chế chế độ ăn, Dị ứng thực phẩm
3. **Thông tin nấu ăn**: Loại bữa ăn quan tâm, Kỹ năng nấu ăn, Thời gian nấu ăn
4. **Sở thích ẩm thực**: Quốc gia yêu thích và các món ăn cụ thể từ 9 quốc gia khác nhau

### 📊 Đặc điểm dữ liệu:
- Dữ liệu từ khảo sát (survey data)
- Nhiều cột có thể chứa nhiều giá trị (phân cách bằng dấu phẩy)
- Một số cột có thể có giá trị null
- Dữ liệu phù hợp để xây dựng user profile cho hệ thống recommendation